# 1. 创建数组

## 1.1 python中的固定类型数组

In [1]:
import array
L = list(range(10))
# array为python内置数组模块，i是一个数据类型码表示数据为整型
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## 1.2 利用np.array从列表创建数组

In [2]:
import numpy as np
import array

In [3]:
np.array([1, 2, 3])

array([1, 2, 3])

In [4]:
# Numpy要求数组必须包含统一类型的数据，类型不匹配会向上转化，可以用dtype明确设置数据类型
a = np.array([3.0, 2, 5, 1.3])
b = np.array([1, 2, 3, 4], dtype = 'float')
print(a)
print(b)
type(b)

[3.  2.  5.  1.3]
[1. 2. 3. 4.]


numpy.ndarray

In [5]:
# 嵌套列表构成多维数组
for i in range(2, 5):
    print(i)

list1 = [range(i, i + 3) for i in [2, 4, 6]]
c = np.array([range(i, i + 3) for i in [2, 4, 6]])
print('list1:', list1)
print(c)
c

2
3
4
list1: [range(2, 5), range(4, 7), range(6, 9)]
[[2 3 4]
 [4 5 6]
 [6 7 8]]


array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## 1.3 从头创建数组

In [6]:
# 用np.zeros创建一个长度为10，值都是整型0的数组
np.zeros(10, dtype = int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [7]:
# 用np.ones创建一个3 X 5的浮点型数组，数组值均为1
np.ones((3, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
# 用np.full创建一个3 X 5的浮点型数组，数值指定都为3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [9]:
# 用np.arange创建一个线性序列数组，数组值从0开始到20结束（不包含20），步长为2，类似与range函数
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
a1 = np.random.random()
print('创建一个[0,1)之间的随机数', a1)
a2 = np.random.random(1)
print('创建一个只包含[0,1)之间一个单一元素的数组', a2)
a3 = np.random.random((3, 3))
print('创建一个[0,1)之间随机数组成的3X3的数组\n', a3)
a4 = np.random.random((2, 3, 4))
print('创建一个[0,1)之间随机数组成的2X3X4的数组\n', a4)
a5 = np.random.uniform(5, 7, (2, 2))
print('创建一个[5,7)之间随机浮点数组成的2X2的数组\n', a5)
a6 = np.random.randint(5, 7, (2, 2))
print('创建一个[5,7)之间随机整数组成的2X2的数组\n', a6)


创建一个[0,1)之间的随机数 0.22374127021817014
创建一个只包含[0,1)之间一个单一元素的数组 [0.84145417]
创建一个[0,1)之间随机数组成的3X3的数组
 [[0.71278402 0.97394052 0.34631557]
 [0.51381328 0.35256354 0.37734188]
 [0.48306871 0.97658375 0.73169681]]
创建一个[0,1)之间随机数组成的2X3X4的数组
 [[[0.1700443  0.67706364 0.71160529 0.29062295]
  [0.36714629 0.52258593 0.55609442 0.86915838]
  [0.33876692 0.7911301  0.20279261 0.48215727]]

 [[0.10381018 0.5237956  0.01934173 0.08847499]
  [0.53557864 0.53785903 0.85962831 0.28247474]
  [0.77428769 0.41936218 0.77381126 0.35738563]]]
创建一个[5,7)之间随机浮点数组成的2X2的数组
 [[5.92123651 5.2043172 ]
 [6.48599486 6.96837035]]
创建一个[5,7)之间随机整数组成的2X2的数组
 [[6 6]
 [5 5]]


In [11]:
# 创建一个3 X 3的均值为0，标准差为1，符合正态分布的随机数数组 np.random.normal(均值，标准差，形状)-------正态分布概率密度函数
np.random.normal(0, 1, (3, 3))

array([[ 0.1794638 ,  0.29924339,  0.78407476],
       [-0.024432  , -1.61568979,  0.26373132],
       [-0.20668012,  0.96809527,  1.28210668]])

In [12]:
# 创建一个3 X 3的数组，包含标准正态分布的随机数
np.random.randn(3, 3)

array([[-1.69147428, -0.45466148,  0.82442674],
       [-0.79313073,  0.06204386,  0.98110504],
       [-0.38922718,  1.59617021,  1.37333743]])

In [13]:
# 创建一个3X3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [14]:
# 创建一个由3个整型数组成的未初始化的数组，数组的值是空间中的任意值
np.empty(3)

array([1., 1., 1.])

# 2. 数组基础

## 2.1 数组属性

In [15]:
# 设置随机数生成种子，确保每次程序执行都生成同样的随机数组
np.random.seed(0)

In [16]:
# 设置随机数生成种子，确保每次程序执行都生成同样的随机数组
x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (3, 4))
x3 = np.random.randint(10, size = (3, 4, 5)) #3层4行5列

In [17]:
x1,x2,x3

(array([5, 0, 3, 3, 7, 9]),
 array([[3, 5, 2, 4],
        [7, 6, 8, 8],
        [1, 6, 7, 7]]),
 array([[[8, 1, 5, 9, 8],
         [9, 4, 3, 0, 3],
         [5, 0, 2, 3, 8],
         [1, 3, 3, 3, 7]],
 
        [[0, 1, 9, 9, 0],
         [4, 7, 3, 2, 7],
         [2, 0, 0, 4, 5],
         [5, 6, 8, 4, 1]],
 
        [[4, 9, 8, 1, 1],
         [7, 9, 9, 3, 6],
         [7, 2, 0, 3, 5],
         [9, 4, 4, 6, 4]]]))

In [18]:
print('x3 ndim: ', x3.ndim) # 数组维度或秩
print('x3.shape:', x3.shape) # 数组形状，每个维度的大小
print('x3.size: ', x3.size) # 数组总大小 各维度大小的乘积
print('x3.dtype: ', x3.dtype) # 数组数据类型
print('x3.itemsize: ', x3.itemsize, 'bytes') # 每个数组元素字节大小
print('x3.nbytes: ', x3.nbytes, 'bytes') # 数组总字节大小  一般nbytes = intemsize * shape

x3 ndim:  3
x3.shape: (3, 4, 5)
x3.size:  60
x3.dtype:  int32
x3.itemsize:  4 bytes
x3.nbytes:  240 bytes


## 2.2 数组索引

In [19]:
x1

array([5, 0, 3, 3, 7, 9])

In [20]:
print(x1[0])
# 用负值获取数组末尾索引
print(x1[-1])


5
9


In [21]:
x3

array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [7, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

In [22]:
x3[2][2][0] # 取第3层第3行第1列的数

7

In [23]:
# 利用索引修改数组的元素值,浮点数插入整型数组时会自动截短
x3[2][2][0] = 10
print(x3)
x3[2][2][0] = 3.1415
x3

[[[ 8  1  5  9  8]
  [ 9  4  3  0  3]
  [ 5  0  2  3  8]
  [ 1  3  3  3  7]]

 [[ 0  1  9  9  0]
  [ 4  7  3  2  7]
  [ 2  0  0  4  5]
  [ 5  6  8  4  1]]

 [[ 4  9  8  1  1]
  [ 7  9  9  3  6]
  [10  2  0  3  5]
  [ 9  4  4  6  4]]]


array([[[8, 1, 5, 9, 8],
        [9, 4, 3, 0, 3],
        [5, 0, 2, 3, 8],
        [1, 3, 3, 3, 7]],

       [[0, 1, 9, 9, 0],
        [4, 7, 3, 2, 7],
        [2, 0, 0, 4, 5],
        [5, 6, 8, 4, 1]],

       [[4, 9, 8, 1, 1],
        [7, 9, 9, 3, 6],
        [3, 2, 0, 3, 5],
        [9, 4, 4, 6, 4]]])

## 2.3 数组切片
Numpy切片语法同列表，x[start:stop:step],默认start=0, step=1, 索引从0开始左边包含，右边不包含。

In [24]:
# 一维数组切片
x = np.arange(10)
print(x)
print('x[:5]', x[:5])
print('x[5:]', x[5:])
print('x[4:7]', x[4:7])
print('每隔一个元素x[::2]', x[::2])
print('从索引1开始每隔一个元素x[1::2]', x[1::2])
# 步长为负逆序排列
print('所有元素逆序x[::-1]', x[::-1])
print('索引5开始逆序每隔一个元素x[5::-2]', x[5::-2])

[0 1 2 3 4 5 6 7 8 9]
x[:5] [0 1 2 3 4]
x[5:] [5 6 7 8 9]
x[4:7] [4 5 6]
每隔一个元素x[::2] [0 2 4 6 8]
从索引1开始每隔一个元素x[1::2] [1 3 5 7 9]
所有元素逆序x[::-1] [9 8 7 6 5 4 3 2 1 0]
索引5开始逆序每隔一个元素x[5::-2] [5 3 1]


In [25]:
print(x2)
print('取前2行前3列x2[:2, :3]\n', x2[:2, :3])
print('取前3行前1列x2[:3, :1]\n', x2[:3, :1])
print('所有行每隔1列x2[:3, ::2]\n',x2[:3, ::2] )
print('逆序x2[::-1, ::-1]\n', x2[::-1, ::-1])
# 获取单行单列简洁语法
print(':表示空切片x2[:, 0]', x2[:, 0])
print('获取单行时列空切片省略x2[1]=x2[1, :]', x2[1])

[[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
取前2行前3列x2[:2, :3]
 [[3 5 2]
 [7 6 8]]
取前3行前1列x2[:3, :1]
 [[3]
 [7]
 [1]]
所有行每隔1列x2[:3, ::2]
 [[3 2]
 [7 8]
 [1 7]]
逆序x2[::-1, ::-1]
 [[7 7 6 1]
 [8 8 6 7]
 [4 2 5 3]]
:表示空切片x2[:, 0] [3 7 1]
获取单行时列空切片省略x2[1]=x2[1, :] [7 6 8 8]


In [26]:
# 数组切片返回的是原数组的视图而不是副本，因此修改数组切片得到的子数组会同时修改原数组的元素值
# 通过copy()函数复制数组,修改复制后的子数组，原数组不会变
print('x2\n', x2)
x2_sub = x2[:2, :2]
x2_sub_copy = x2[:2, :2].copy()
print('子数组x2_sub\n', x2_sub)
x2_sub[0,:] = 9
print('子数组x2_sub\n', x2_sub)
print('修改了子数组后的x2\n', x2)
x2_sub_copy[0,:] = 1
print('子数组x2_sub_copy\n', x2_sub_copy)
print('修改了子数组副本的x2\n', x2)

x2
 [[3 5 2 4]
 [7 6 8 8]
 [1 6 7 7]]
子数组x2_sub
 [[3 5]
 [7 6]]
子数组x2_sub
 [[9 9]
 [7 6]]
修改了子数组后的x2
 [[9 9 2 4]
 [7 6 8 8]
 [1 6 7 7]]
子数组x2_sub_copy
 [[1 1]
 [7 6]]
修改了子数组副本的x2
 [[9 9 2 4]
 [7 6 8 8]
 [1 6 7 7]]


## 2.4 数组变形

In [27]:
# 将数字1-9放入一个3X3的矩阵，前提是两个数组的大小相同
grid = np.arange(1, 10)
print(grid)
grid_reshape = np.arange(1, 10).reshape(3, 3)
print(grid_reshape)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
x = np.array([1, 2, 3])
# 利用 reshape 或 np.newaxis切片 将一维数组变为二维单行数组
print(x.reshape(1, 3))
print(x[np.newaxis, :])
# 利用 reshape 或 np.newaxis切片 将一维数组变为二维单列数组
print(x.reshape(3, 1))
print(x[:, np.newaxis])

[[1 2 3]]
[[1 2 3]]
[[1]
 [2]
 [3]]
[[1]
 [2]
 [3]]


## 2.5 数组的拼接和分裂

In [29]:
# 一维数组的拼接
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))
# 二维数组的拼接, np.concatennate([x, y], axis默认是0沿着行方向对每列操作，1是沿着列方向对每行操作)要求维度相同
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])
print(np.concatenate([grid, grid]))
print(np.concatenate([grid, grid], axis = 1))
print('np.vstack垂直栈同axis=0\n', np.vstack([x, y, z, grid]))
print('np.hstack水平栈同axis=1\n', np.hstack([grid, grid]))
# np.dstack沿第三个方向拼接数组

[ 1  2  3  3  2  1 99 99 99]
[[1 2 3]
 [4 5 6]
 [1 2 3]
 [4 5 6]]
[[1 2 3 1 2 3]
 [4 5 6 4 5 6]]
np.vstack垂直栈同axis=0
 [[ 1  2  3]
 [ 3  2  1]
 [99 99 99]
 [ 1  2  3]
 [ 4  5  6]]
np.hstack水平栈同axis=1
 [[1 2 3 1 2 3]
 [4 5 6 4 5 6]]


In [30]:
x = [0, 1, 2, 3, 4, 5, 6, 7, 8]
x1, x2, x3 = np.split(x, [3, 5]) # np.split(x, [索引列表记录断点位置])，N个分裂点得到N+1个数组
print(x1, x2, x3)
y = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
print('沿行方向平均分裂成3个数组\n', np.split(y, 3))
print('沿列方向平均分裂成3个数组\n', np.split(y, 3, axis = 1))
# print('沿行方向平均分裂成3个数组\n', np.split(y, [1, 2]))---------------待解释
grid = np.arange(16).reshape(4, 4)
print(grid)
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)
left, right = np.hsplit(grid, [1])
print(left)
print(right)

[0 1 2] [3 4] [5 6 7 8]
沿行方向平均分裂成3个数组
 [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
沿列方向平均分裂成3个数组
 [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]
[[ 0]
 [ 4]
 [ 8]
 [12]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]


# 3. Numpy数组的计算：通用函数
一元通用函数对单个输入操作，二元通用函数对两个输入操作


## 3.1 常用通用函数
数组的运算

In [31]:
x = np.arange(4)
print('x    = ', x)
print('x + 5 =', x + 5, np.add(x, 5))
print('x - 5 =', x - 5, np.subtract(x, 5))
print('x * 2 =', x * 2, np.multiply(x, 2))
print('x / 2 =', x / 2, np.divide(x, 2))
print('x // 2 =', x // 2, np.floor_divide(x, 2)) # 取商
print('x % 2 =', x % 2, np.mod(x, 2)) # 取余
print('x ** 2 =', x ** 2, np.power(x, 2))
print('-x     =', -x, np.negative(x))
print('-(0.5*x + 1) ** 2 = ', -(0.5*x + 1) ** 2)

x    =  [0 1 2 3]
x + 5 = [5 6 7 8] [5 6 7 8]
x - 5 = [-5 -4 -3 -2] [-5 -4 -3 -2]
x * 2 = [0 2 4 6] [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5] [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1] [0 0 1 1]
x % 2 = [0 1 0 1] [0 1 0 1]
x ** 2 = [0 1 4 9] [0 1 4 9]
-x     = [ 0 -1 -2 -3] [ 0 -1 -2 -3]
-(0.5*x + 1) ** 2 =  [-1.   -2.25 -4.   -6.25]


绝对值

In [32]:
x = np.array([-2, -1, 0, 1, 2])
print(abs(x))
print(np.abs(x))
print(np.absolute(x))
# 复数的绝对值返回该复数的模，即实部和虚部平方和的平方根
y = np.array([3 - 4j, 4 - 3j, 2 + 0j, 0 + 1j])
print(y)
print(abs(y))


[2 1 0 1 2]
[2 1 0 1 2]
[2 1 0 1 2]
[3.-4.j 4.-3.j 2.+0.j 0.+1.j]
[5. 5. 2. 1.]


三角函数和逆三角函数

In [33]:
# numpy.linspace(start, stop, num=50, endpoint=True(stop值包含在数组中), retstep=False, dtype=None, axis=0)
# np.pi = π
theta = np.linspace(0, np.pi, 3)
print('theta      = ', theta)
print('sin(theta) = ', np.sin(theta))
print('cos(theta) = ', np.cos(theta))
print('tan(theta) = ', np.tan(theta))
x = [-1, 0, 1]
print('x      = ', x)
print('arcsin(x) = ', np.arcsin(x))
print('arccos(x) = ', np.arccos(x))
print('arctan(x) = ', np.arctan(x))

theta      =  [0.         1.57079633 3.14159265]
sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]
x      =  [-1, 0, 1]
arcsin(x) =  [-1.57079633  0.          1.57079633]
arccos(x) =  [3.14159265 1.57079633 0.        ]
arctan(x) =  [-0.78539816  0.          0.78539816]


指数和对数

In [34]:
x = [1, 2, 3]
print('x = ', x)
print('e^x = ', np.exp(x))
print('2^x = ', np.exp2(x))
print('3^x = ', np.power(3, x))
y = [1, 2, 4, 10]
print('y = ', y)
print('ln(x) = ', np.log(x)) # np.log以自然常数（e）为底数的对数
print('log2(x) = ', np.log2(x))
print('log10(x) = ', np.log10(x))
# 特殊版本，当输入值非常小时，用特殊函数给出的值比np.log和np.exp计算更精确
z = [0, 0.001, 0.01, 0.1]
print('exp(z) - 1 = ', np.expm1(z))
print('log(1 + z) = ', np.log1p(z))

x =  [1, 2, 3]
e^x =  [ 2.71828183  7.3890561  20.08553692]
2^x =  [2. 4. 8.]
3^x =  [ 3  9 27]
y =  [1, 2, 4, 10]
ln(x) =  [0.         0.69314718 1.09861229]
log2(x) =  [0.        1.        1.5849625]
log10(x) =  [0.         0.30103    0.47712125]
exp(z) - 1 =  [0.         0.0010005  0.01005017 0.10517092]
log(1 + z) =  [0.         0.0009995  0.00995033 0.09531018]


In [35]:
# 专用通用函数
# Gamma函数（广义阶乘）和相关函数
from scipy import special
x = [1, 5, 10]
print('gamma(x)     = ', special.gamma(x))
print('ln|gamma(x)| = ', special.gammaln(x))
print('beta(x, 2)   = ', special.beta(x, 2))
# 误差函数（高斯积分）实现与逆实现
y = np.array([0, 0.3, 0.7, 1.0])
print('erf(y) = ', special.erf(y))
print('erfc(y) = ', special.erfc(y))
print('erfinv(y) = ', special.erfinv(y))

gamma(x)     =  [1.0000e+00 2.4000e+01 3.6288e+05]
ln|gamma(x)| =  [ 0.          3.17805383 12.80182748]
beta(x, 2)   =  [0.5        0.03333333 0.00909091]
erf(y) =  [0.         0.32862676 0.67780119 0.84270079]
erfc(y) =  [1.         0.67137324 0.32219881 0.15729921]
erfinv(y) =  [0.         0.27246271 0.73286908        inf]


## 3.2 高级的通用函数特性
1. 指定输出位置：所有通用函数都可以用out参数指定计算结果的存放位置


In [36]:
x = np.arange(5)
y = np.empty(5)
np.multiply(x, 10, out = y)
print(y)
# 将计算结果写入指定数组的每隔一个元素的位置
z = np.zeros(10)
print(z)
print(np.power(2, x, out = z[::2]))
print(z)

[ 0. 10. 20. 30. 40.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[ 1.  2.  4.  8. 16.]
[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


2. 聚合reduce：所有元素累积

In [37]:
x = np.arange(1, 6)
print('x = ', x)
print('x中所有元素求和：', np.add.reduce(x))
print('x中所有元素求积：', np.multiply.reduce(x))
print('x中所有元素依次求和并展示：', np.add.accumulate(x))
print('x中所有元素依次求积并展示：', np.multiply.accumulate(x))

x =  [1 2 3 4 5]
x中所有元素求和： 15
x中所有元素求积： 120
x中所有元素依次求和并展示： [ 1  3  6 10 15]
x中所有元素依次求积并展示： [  1   2   6  24 120]


3. 外积：outer获得两个不同输入数组所有元素对的函数运算结果

In [38]:
x = np.arange(1, 6)
print('x = ', x)
print(np.multiply.outer(x, x))

x =  [1 2 3 4 5]
[[ 1  2  3  4  5]
 [ 2  4  6  8 10]
 [ 3  6  9 12 15]
 [ 4  8 12 16 20]
 [ 5 10 15 20 25]]


In [39]:
import numpy as np
a=np.arange(1,19)
b=np.arange(19,49)
print(a)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18]
[19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42
 43 44 45 46 47 48]


In [40]:
A=a.reshape(3,6)
B=b.reshape(5,6)
print(A)
print()
print(B)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]]

[[19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [41]:
C=np.vstack([A,B])
print(C)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [42]:
upper, lower = np.vsplit(C, [1])
D=lower
print(D)


[[ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]
 [37 38 39 40 41 42]
 [43 44 45 46 47 48]]


In [43]:
E=D[:1:]
print(E)

[[ 7  8  9 10 11 12]]


In [44]:
E_flattened = E.flatten()
a1=np.multiply.accumulate(E_flattened)
a1

array([     7,     56,    504,   5040,  55440, 665280])

In [45]:

def save_csv(a1):
    import pandas as pd
    df = pd.DataFrame({"id": ["q1"], "answer": [a1]})
    df.to_csv("answer_1.csv", index=None)

save_csv(a1)  # 运行这个cell,生成答案文件；该文件在左侧文件树project工作区下，你可以自行右击下载或者读取查看

In [46]:
!wget -nv -O heywhale_submit https://cdn.kesci.com/submit_tool/v4/heywhale_submit&&chmod +x heywhale_submit

'wget' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���


In [47]:
!./heywhale_submit -token c985c27ac9c7df76 -file answer_1.csv  

'.' �����ڲ����ⲿ���Ҳ���ǿ����еij���
���������ļ���
